[package]
name = "iris-diagnostics"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
building-types = { version = "0.1.0", path = "../../compiler-core/building-types" }
files = { version = "0.1.0", path = "../../compiler-core/files" }
foreign-javascript = { version = "0.1.0", path = "../../compiler-backend/foreign-javascript" }
functional = { version = "0.1.0", path = "../../compiler-backend/functional" }
indexing = { version = "0.1.0", path = "../../compiler-frontend/indexing" }
javascript = { version = "0.1.0", path = "../../compiler-backend/javascript" }
lowering = { version = "0.1.0", path = "../../compiler-frontend/lowering" }
resolving = { version = "0.1.0", path = "../../compiler-frontend/resolving" }
checking = { version = "0.1.0", path = "../../compiler-frontend/checking" }
stabilizing = { version = "0.1.0", path = "../../compiler-frontend/stabilizing" }
syntax = { version = "0.1.0", path = "../../compiler-frontend/syntax" }

lsp-types.workspace = true
line-index = "0.1.2"
itertools = "0.15.0"
smol_str = "0.3.6"
textwrap = "0.16.4"
unicode-width = "0.2.2"
