[package]
name = "tests-compatibility"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[dependencies]
anyhow = "1"
building = { version = "0.1.0", path = "../compiler-core/building" }
checking = { version = "0.1.0", path = "../compiler-frontend/checking" }
clap = { version = "4", features = ["derive"] }
criterion = { version = "0.8.2", features = ["html_reports"] }
diagnostics = { version = "0.1.0", path = "../compiler-frontend/diagnostics" }
files = { version = "0.1.0", path = "../compiler-core/files" }
flate2 = "1"
git2 = { version = "0.21", features = ["https"] }
globset = "0.4.20"
indicatif = "0.18.6"
indexing = { version = "0.1.0", path = "../compiler-frontend/indexing" }
lexing = { version = "0.1.0", path = "../compiler-frontend/lexing" }
line-index = "0.1.2"
lowering = { version = "0.1.0", path = "../compiler-frontend/lowering" }
mimalloc = "0.1.52"
parsing = { version = "0.1.0", path = "../compiler-frontend/parsing" }
rayon = "1.12.0"
reqwest = { version = "0.13", default-features = false, features = ["blocking", "rustls"] }
resolving = { version = "0.1.0", path = "../compiler-frontend/resolving" }
semver = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
stabilizing = { version = "0.1.0", path = "../compiler-frontend/stabilizing" }
syntax = { version = "0.1.0", path = "../compiler-frontend/syntax" }
tar = "0.4.46"
thiserror = "2"
url = "2.5.8"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3"

[[bench]]
name = "parsing"
harness = false

[[bench]]
name = "stabilizing"
harness = false

[[bench]]
name = "checking_single_core"
harness = false

[[bench]]
name = "checking_multi_core"
harness = false
