mod convert;
mod pretty;

use std::iter;

use building_types::QueryResult;
use files::FileId;
use indexing::TermItemId;
use itertools::Itertools;
use rustc_hash::FxHashSet;
use smol_str::SmolStr;

use crate::context::CheckContext;
use crate::core::substitute::SubstituteName;
use crate::core::{Type, TypeId, normalise, toolkit};
use crate::state::CheckState;
use crate::{ExternalQueries, safe_loop};

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Pattern {
    pub kind: PatternKind,
    pub t: TypeId,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum PatternKind {
    Wildcard,
    Constructor { constructor: PatternConstructor },
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum PatternConstructor {
    DataConstructor { file_id: FileId, item_id: TermItemId, fields: Vec<PatternId> },
    Record { labels: Vec<SmolStr>, fields: Vec<PatternId> },
    Array { fields: Vec<PatternId> },
    Boolean(bool),
    Integer(i32),
    Number(bool, SmolStr),
    String(lowering::StringLiteral),
    Char(char),
}

impl PatternConstructor {
    /// Returns the arity of this pattern constructor.
    ///
    /// [`PatternConstructor::DataConstructor`], [`PatternConstructor::Record`],
    /// and [`PatternConstructor::Array`] have non-zero arity based on their fields.
    pub fn arity(&self) -> usize {
        match self {
            PatternConstructor::DataConstructor { fields, .. } => fields.len(),
            PatternConstructor::Record { fields, .. } => fields.len(),
            PatternConstructor::Array { fields } => fields.len(),
            _ => 0,
        }
    }

    /// Returns the fields of this pattern constructor.
    ///
    /// [`PatternConstructor::DataConstructor`], [`PatternConstructor::Record`],
    /// and [`PatternConstructor::Array`] have fields corresponding to their arguments.
    pub fn fields(&self) -> &[PatternId] {
        match self {
            PatternConstructor::DataConstructor { fields, .. } => fields,
            PatternConstructor::Record { fields, .. } => fields,
            PatternConstructor::Array { fields } => fields,
            _ => &[],
        }
    }

    /// Checks if a pattern constructor matches another.
    ///
    /// This is used during the specialisation algorithm to determine if a
    /// pattern row should be included in the specialised pattern matrix.
    pub fn matches(&self, other: &PatternConstructor) -> bool {
        match (self, other) {
            (
                PatternConstructor::DataConstructor { file_id: f1, item_id: i1, .. },
                PatternConstructor::DataConstructor { file_id: f2, item_id: i2, .. },
            ) => f1 == f2 && i1 == i2,
            // Any record constructor matches any other record constructor
            (PatternConstructor::Record { .. }, PatternConstructor::Record { .. }) => true,
            // Array constructors match only when their lengths match
            (
                PatternConstructor::Array { fields: f1 },
                PatternConstructor::Array { fields: f2 },
            ) => f1.len() == f2.len(),
            (PatternConstructor::Boolean(b1), PatternConstructor::Boolean(b2)) => b1 == b2,
            (PatternConstructor::Integer(i1), PatternConstructor::Integer(i2)) => i1 == i2,
            (PatternConstructor::Number(n1, v1), PatternConstructor::Number(n2, v2)) => {
                n1 == n2 && v1 == v2
            }
            (PatternConstructor::String(s1), PatternConstructor::String(s2)) => s1 == s2,
            (PatternConstructor::Char(c1), PatternConstructor::Char(c2)) => c1 == c2,
            _ => false,
        }
    }

    /// Reconstructs a [`PatternConstructor`] with the given fields.
    ///
    /// For [`PatternConstructor::DataConstructor`], [`PatternConstructor::Record`],
    /// and [`PatternConstructor::Array`], this function overrides the fields.
    /// Otherwise, the fields must be empty as enforced by an assertion.
    ///
    /// This algorithm is used in [`algorithm_m`] to replace the fields of the
    /// pattern constructor we're specialising on with the fields generated by
    /// the witnesses.
    pub fn reconstruct(&self, fields: &[PatternId]) -> PatternConstructor {
        match *self {
            PatternConstructor::DataConstructor { file_id, item_id, .. } => {
                let fields = fields.to_vec();
                PatternConstructor::DataConstructor { file_id, item_id, fields }
            }
            PatternConstructor::Record { ref labels, .. } => {
                let fields = fields.to_vec();
                PatternConstructor::Record { labels: labels.clone(), fields }
            }
            PatternConstructor::Array { .. } => {
                let fields = fields.to_vec();
                PatternConstructor::Array { fields }
            }
            PatternConstructor::Boolean(b) => {
                assert!(fields.is_empty(), "Boolean constructor has arity 0");
                PatternConstructor::Boolean(b)
            }
            PatternConstructor::Integer(i) => {
                assert!(fields.is_empty(), "Integer constructor has arity 0");
                PatternConstructor::Integer(i)
            }
            PatternConstructor::Number(negative, ref n) => {
                assert!(fields.is_empty(), "Number constructor has arity 0");
                PatternConstructor::Number(negative, SmolStr::clone(n))
            }
            PatternConstructor::String(ref s) => {
                assert!(fields.is_empty(), "String constructor has arity 0");
                PatternConstructor::String(s.clone())
            }
            PatternConstructor::Char(c) => {
                assert!(fields.is_empty(), "Char constructor has arity 0");
                PatternConstructor::Char(c)
            }
        }
    }
}

impl MissingConstructor {
    /// Constructs a witness pattern for this missing constructor.
    pub fn construct_missing_witness(&self, state: &mut CheckState, t: TypeId) -> PatternId {
        match *self {
            MissingConstructor::DataConstructor { file_id, item_id, ref fields } => {
                let fields = fields
                    .iter()
                    .map(|&field_type| state.allocate_wildcard(field_type))
                    .collect_vec();

                let constructor = PatternConstructor::DataConstructor { file_id, item_id, fields };
                let pattern = PatternKind::Constructor { constructor };

                state.allocate_pattern(pattern, t)
            }
            MissingConstructor::Boolean(b) => {
                let constructor = PatternConstructor::Boolean(b);
                let pattern = PatternKind::Constructor { constructor };
                state.allocate_pattern(pattern, t)
            }
        }
    }
}

pub type PatternId = interner::Id<Pattern>;
pub type PatternInterner = interner::Interner<Pattern>;

type PatternVector = Vec<PatternId>;
pub type WitnessVector = Vec<PatternId>;

struct PatternMatrix {
    cells: Vec<PatternId>,
    rows: usize,
    columns: usize,
}

impl PatternMatrix {
    fn new(columns: usize) -> PatternMatrix {
        PatternMatrix { cells: vec![], rows: 0, columns }
    }

    fn with_capacity(columns: usize, rows: usize) -> PatternMatrix {
        let cells = Vec::with_capacity(columns * rows);
        PatternMatrix { cells, rows: 0, columns }
    }

    fn is_empty(&self) -> bool {
        self.rows == 0
    }

    fn iter(&self) -> PatternRows<'_> {
        PatternRows { matrix: self, remaining: self.rows, cell: 0 }
    }

    fn push(&mut self, row: &[PatternId]) {
        assert_eq!(row.len(), self.columns);
        self.cells.extend_from_slice(row);
        self.rows += 1;
    }

    fn normalise_recovery_row<F>(&self, row: &mut PatternVector, mut missing: F)
    where
        F: FnMut(usize) -> PatternId,
    {
        row.truncate(self.columns);
        let missing_columns = row.len()..self.columns;
        row.extend(missing_columns.map(&mut missing));
    }
}

struct PatternRows<'a> {
    matrix: &'a PatternMatrix,
    remaining: usize,
    cell: usize,
}

impl<'a> Iterator for PatternRows<'a> {
    type Item = &'a [PatternId];

    fn next(&mut self) -> Option<&'a [PatternId]> {
        if self.remaining == 0 {
            return None;
        }
        let end = self.cell + self.matrix.columns;
        let row = &self.matrix.cells[self.cell..end];
        self.cell = end;
        self.remaining -= 1;
        Some(row)
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        (self.remaining, Some(self.remaining))
    }
}

impl ExactSizeIterator for PatternRows<'_> {}

impl<'a> IntoIterator for &'a PatternMatrix {
    type Item = &'a [PatternId];
    type IntoIter = PatternRows<'a>;

    fn into_iter(self) -> PatternRows<'a> {
        self.iter()
    }
}

/// Determines if a [`PatternVector`] is useful with respect to a [`PatternMatrix`].
///
/// A pattern vector is useful if it matches at least one value not matched by
/// any pattern vector in the matrix. This is one of the core algorithms from
/// Maranget's "Warnings for pattern matching" paper.
///
/// See [`algorithm_u_constructor`] and [`algorithm_u_wildcard`] for reference.
fn algorithm_u<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    matrix: &PatternMatrix,
    vector: &[PatternId],
) -> QueryResult<bool>
where
    Q: ExternalQueries,
{
    // Base case: any pattern is useful against an empty matrix
    if matrix.is_empty() {
        return Ok(true);
    }

    // Base case: an empty pattern vector against non-empty matrix is useless
    let [first_pattern, ..] = vector[..] else {
        return Ok(false);
    };

    let first_pattern = state.patterns[first_pattern].clone();

    match first_pattern.kind {
        PatternKind::Constructor { constructor } => {
            algorithm_u_constructor(state, context, matrix, vector, constructor)
        }
        PatternKind::Wildcard => algorithm_u_wildcard(state, context, matrix, vector),
    }
}

/// Induction 1
///
/// This function uses specialisation to spread the provided [`PatternConstructor`]
/// over both the [`PatternMatrix`] and the [`PatternVector`], before calling
/// [`algorithm_u`] recursively with the specialised structures.
fn algorithm_u_constructor<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    matrix: &PatternMatrix,
    vector: &[PatternId],
    constructor: PatternConstructor,
) -> QueryResult<bool>
where
    Q: ExternalQueries,
{
    let constructor = canonicalise_record_constructor(state, constructor, matrix);
    let specialised_matrix = specialise_matrix(state, &constructor, matrix);

    let Some(specialised_vector) = specialise_vector(state, &constructor, vector) else {
        unreachable!("invariant violated: vector contains constructor");
    };

    algorithm_u(state, context, &specialised_matrix, &specialised_vector)
}

/// Induction 2
///
/// This function collects all constructor references from the first column of
/// the matrix into a collection called the sigma.
///
/// If the sigma is complete, for each constructor in the sigma, we specialise
/// the pattern matrix and pattern vector against it. Then, we recursively call
/// [`algorithm_u`] against the specialised structures. The pattern vector is
/// useful if any specialised pattern vector is useful against its specialised
/// pattern matrix.
///
/// If the sigma is incomplete, we recursively call [`algorithm_u`] against the
/// [`default_matrix`] of the pattern matrix and the tail of the pattern vector.
fn algorithm_u_wildcard<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    matrix: &PatternMatrix,
    vector: &[PatternId],
) -> QueryResult<bool>
where
    Q: ExternalQueries,
{
    let sigma = collect_sigma(state, matrix);
    let complete = sigma_is_complete(context, &sigma)?;

    if complete {
        algorithm_u_wildcard_complete(state, context, matrix, vector, sigma)
    } else {
        algorithm_u_wildcard_incomplete(state, context, matrix, vector)
    }
}

fn algorithm_u_wildcard_complete<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    matrix: &PatternMatrix,
    vector: &[PatternId],
    sigma: Sigma,
) -> QueryResult<bool>
where
    Q: ExternalQueries,
{
    for constructor in sigma.constructors {
        let specialised_matrix = specialise_matrix(state, &constructor, matrix);

        let Some(specialised_vector) = specialise_vector(state, &constructor, vector) else {
            unreachable!("invariant violated: vector contains constructor");
        };

        if algorithm_u(state, context, &specialised_matrix, &specialised_vector)? {
            return Ok(true);
        }
    }
    Ok(false)
}

fn algorithm_u_wildcard_incomplete<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    matrix: &PatternMatrix,
    vector: &[PatternId],
) -> QueryResult<bool>
where
    Q: ExternalQueries,
{
    let default = default_matrix(state, matrix);
    let tail_columns = vector[1..].to_vec();
    algorithm_u(state, context, &default, &tail_columns)
}

/// Determines the matching [`WitnessVector`] given a [`PatternMatrix`]
/// and some [`PatternVector`].
///
/// If the pattern vector is useful against the provided matrix, that is,
/// there are cases yet to be covered, this function will return a non-empty
/// list of witnesses. Inversely, if the pattern vector is useless against
/// the provided matrix, that is, the cases are exhaustive, this function
/// will return [`None`].
///
/// So... what exactly are witnesses? In the paper, these are defined as
/// 'value vectors' that are known not to be matched against the pattern
/// matrix but are instantiations of the pattern vector. In our implementation,
/// these witnesses are pattern vectors that denote values not yet covered by
/// the matrix.
///
/// The [`algorithm_m_wildcard`] induction is prolific for producing these
/// these witnesses as it compares the constructors that appear in the
/// matrix against the constructors available in the checking environment.
fn algorithm_m<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    matrix: &PatternMatrix,
    vector: &[PatternId],
) -> QueryResult<Option<Vec<WitnessVector>>>
where
    Q: ExternalQueries,
{
    // Base case: any pattern is its own witness against an empty matrix
    if matrix.is_empty() {
        let vector = vector.to_vec();
        return Ok(Some(vec![vector]));
    }

    // Base case: an empty pattern vector against non-empty matrix has no witnesses
    let [first_pattern, ..] = vector[..] else {
        return Ok(None);
    };

    let first_pattern = state.patterns[first_pattern].clone();

    match first_pattern.kind {
        PatternKind::Constructor { constructor } => {
            algorithm_m_constructor(state, context, matrix, vector, constructor, first_pattern.t)
        }
        PatternKind::Wildcard => {
            algorithm_m_wildcard(state, context, matrix, vector, first_pattern.t)
        }
    }
}

/// Induction 1
///
/// This function uses specialisation to spread the provided [`PatternConstructor`]
/// over both the [`PatternMatrix`] and the [`PatternVector`], before calling
/// [`algorithm_m`] recursively with the specialised structures.
///
/// The final set of witnesses returned by this induction includes a
/// reconstruction of the original constructor passed to this function.
///
/// See documentation for [`specialise_matrix`] and [`specialise_vector`] for
/// more information on what specialisation entails given a constructor.
fn algorithm_m_constructor<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    matrix: &PatternMatrix,
    vector: &[PatternId],
    constructor: PatternConstructor,
    t: TypeId,
) -> QueryResult<Option<Vec<WitnessVector>>>
where
    Q: ExternalQueries,
{
    let constructor = canonicalise_record_constructor(state, constructor, matrix);
    let arity = constructor.arity();

    let specialised_matrix = specialise_matrix(state, &constructor, matrix);

    let Some(specialised_vector) = specialise_vector(state, &constructor, vector) else {
        unreachable!("invariant violated: vector contains constructor");
    };

    let witnesses = algorithm_m(state, context, &specialised_matrix, &specialised_vector)?;

    let Some(witnesses) = witnesses else {
        return Ok(None);
    };

    let witnesses = witnesses.into_iter().map(|witness| {
        let (argument_columns, tail_columns) = witness.split_at(arity);

        let constructor = constructor.reconstruct(argument_columns);
        let constructor_id = state.allocate_constructor(constructor, t);
        let tail_columns = tail_columns.iter().copied();

        iter::once(constructor_id).chain(tail_columns).collect()
    });

    let witnesses = witnesses.collect();
    Ok(Some(witnesses))
}

/// Induction 2
///
/// If the first column in the [`PatternVector`] is a wildcard, this function
/// produces witnesses that correspond to patterns not yet covered by the
/// [`PatternMatrix`]. This is where pattern suggestion warnings are built
/// for the compiler!
///
/// This function collects all constructor references from the first column
/// of all rows in the matrix into a collection called the sigma. We handle
/// the structure in different ways:
///
/// If the sigma is complete, for each constructor in the sigma, we apply
/// a rule similar to [`algorithm_m_constructor`] to collect witnesses
/// across all constructors.
///
/// If the sigma is incomplete, we recursively apply [`algorithm_m`] to the
/// [`default_matrix`] of the pattern matrix and the tail columns of the
/// pattern vector. The induction ends if the recursive call is exhaustive.
///
/// If the recursive call returns witnesses, and the sigma is non-empty,
/// we move our attention to generating [`Constructor`] patterns for
/// constructors not present in the sigma. This is what we use for
/// reporting pattern warnings. Otherwise, if the sigma is empty, we
/// simply produce a wildcard pattern.
fn algorithm_m_wildcard<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    matrix: &PatternMatrix,
    vector: &[PatternId],
    t: TypeId,
) -> QueryResult<Option<Vec<WitnessVector>>>
where
    Q: ExternalQueries,
{
    let sigma = collect_sigma(state, matrix);
    let complete = sigma_is_complete(context, &sigma)?;
    if complete {
        algorithm_m_wildcard_complete(state, context, matrix, vector, t, &sigma)
    } else {
        algorithm_m_wildcard_incomplete(state, context, matrix, vector, t, &sigma)
    }
}

fn algorithm_m_wildcard_complete<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    matrix: &PatternMatrix,
    vector: &[PatternId],
    t: TypeId,
    sigma: &Sigma,
) -> QueryResult<Option<Vec<WitnessVector>>>
where
    Q: ExternalQueries,
{
    let mut all_witnesses = vec![];

    for constructor in &sigma.constructors {
        let arity = constructor.arity();

        let specialised_matrix = specialise_matrix(state, constructor, matrix);

        let Some(specialised_vector) = specialise_vector(state, constructor, vector) else {
            unreachable!("invariant violated: vector contains constructor");
        };

        if let Some(witnesses) =
            algorithm_m(state, context, &specialised_matrix, &specialised_vector)?
        {
            for witness in witnesses {
                let (argument_columns, tail_columns) = witness.split_at(arity);

                let constructor = constructor.reconstruct(argument_columns);
                let constructor_id = state.allocate_constructor(constructor, t);
                let tail_columns = tail_columns.iter().copied();

                let witnesses = iter::once(constructor_id).chain(tail_columns).collect();
                all_witnesses.push(witnesses);
            }
        }
    }

    if all_witnesses.is_empty() { Ok(None) } else { Ok(Some(all_witnesses)) }
}

fn algorithm_m_wildcard_incomplete<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    matrix: &PatternMatrix,
    vector: &[PatternId],
    t: TypeId,
    sigma: &Sigma,
) -> QueryResult<Option<Vec<WitnessVector>>>
where
    Q: ExternalQueries,
{
    let default = default_matrix(state, matrix);
    let tail_columns = vector[1..].to_vec();

    let witnesses = algorithm_m(state, context, &default, &tail_columns)?;

    let Some(witnesses) = witnesses else {
        return Ok(None);
    };

    // Only the first missing constructor is reported, so the others are
    // never instantiated.
    let missing = first_missing_constructor(state, context, t, &sigma.constructors)?;
    let first_column = if let Some(constructor) = missing {
        constructor.construct_missing_witness(state, t)
    } else {
        state.allocate_wildcard(t)
    };

    let witness = witnesses
        .into_iter()
        .map(|witness| iter::once(first_column).chain(witness).collect())
        .collect();

    Ok(Some(witness))
}

/// Computes a canonical [`PatternConstructor::Record`] that includes the union of all
/// record labels appearing in the first column of the matrix and the given constructor.
///
/// Record patterns in PureScript can mention different subsets of the full row type.
/// For example, `{ a }` and `{ a, b }` both match `{ a :: Int, b :: Int }`, but they
/// produce record constructors with different arities. The specialisation algorithm
/// requires all rows to have the same width, so we normalise to a canonical label set
/// before specialising.
///
/// For non-record constructors this function returns the constructor unchanged.
fn canonicalise_record_constructor(
    state: &CheckState,
    constructor: PatternConstructor,
    matrix: &PatternMatrix,
) -> PatternConstructor {
    let PatternConstructor::Record { labels, fields } = &constructor else {
        return constructor;
    };

    let mut canonical = {
        let labels = labels.iter().cloned();
        let fields = fields.iter().copied();
        labels.zip(fields).collect_vec()
    };

    let initial_length = canonical.len();

    for row in matrix {
        let Some(&first) = row.first() else {
            continue;
        };

        if let PatternKind::Constructor {
            constructor: PatternConstructor::Record { labels, fields },
        } = &state.patterns[first].kind
        {
            for (label, &field) in iter::zip(labels, fields) {
                if !canonical.iter().any(|(existing, _)| existing == label) {
                    canonical.push((label.clone(), field));
                }
            }
        }
    }

    if canonical.len() == initial_length {
        return constructor;
    }

    // Subtle: stable sorting by label
    canonical.sort_by(|(a, _), (b, _)| a.cmp(b));

    let (labels, fields) = canonical.into_iter().unzip();
    PatternConstructor::Record { labels, fields }
}

/// Specialises a [`PatternMatrix`] given a [`PatternConstructor`].
///
/// See documentation below for [`specialise_vector`].
fn specialise_matrix(
    state: &mut CheckState,
    expected: &PatternConstructor,
    matrix: &PatternMatrix,
) -> PatternMatrix {
    let columns = matrix.columns - 1 + expected.arity();
    let mut specialised_matrix = if columns == 0 {
        PatternMatrix::new(0)
    } else {
        let matching_rows =
            matrix.iter().filter(|row| vector_matches_constructor(state, expected, row)).count();
        PatternMatrix::with_capacity(columns, matching_rows)
    };
    for row in matrix {
        let initial_length = specialised_matrix.cells.len();
        if specialise_vector_into(state, expected, row, &mut specialised_matrix.cells) {
            assert_eq!(specialised_matrix.cells.len() - initial_length, specialised_matrix.columns);
            specialised_matrix.rows += 1;
        } else {
            specialised_matrix.cells.truncate(initial_length);
        }
    }
    specialised_matrix
}

fn vector_matches_constructor(
    state: &CheckState,
    expected: &PatternConstructor,
    vector: &[PatternId],
) -> bool {
    let [first_column_id, ..] = vector else {
        unreachable!("invariant violated: vector_matches_constructor processed empty row");
    };
    match &state.patterns[*first_column_id].kind {
        PatternKind::Wildcard => true,
        PatternKind::Constructor { constructor } => constructor.matches(expected),
    }
}

/// Specialises a [`PatternVector`] given a [`PatternConstructor`].
///
/// Specialisation takes a pattern vector and applies the following rules:
/// 1. If the first column is a wildcard, it expands it to `n` wildcards
///    where `n` is the arity of the expected [`PatternConstructor`].
///    For non-ADT constructors, arity is 0 (no expansion needed).
/// 2. It returns `None` for constructors that are not the expected
///    [`PatternConstructor`], which excludes them from the specialised matrix.
///    For example, a pattern vector specialised on `Just` removes `Nothing`.
/// 3. For matching constructors, it 'splats' the fields, effectively turning
///    a pattern vector like `[Just _]` into `[_]` or `[Nothing]` into `[]`.
///    For non-ADT constructors, arity is 0 so nothing is splatted.
fn specialise_vector(
    state: &mut CheckState,
    expected: &PatternConstructor,
    vector: &[PatternId],
) -> Option<PatternVector> {
    let mut specialised = Vec::with_capacity(vector.len() - 1 + expected.arity());
    if specialise_vector_into(state, expected, vector, &mut specialised) {
        Some(specialised)
    } else {
        None
    }
}

fn specialise_vector_into(
    state: &mut CheckState,
    expected: &PatternConstructor,
    vector: &[PatternId],
    specialised: &mut PatternVector,
) -> bool {
    let [first_column_id, ref tail_columns @ ..] = vector[..] else {
        unreachable!("invariant violated: specialise_vector processed empty row");
    };

    let initial_length = specialised.len();

    match &state.patterns[first_column_id].kind {
        PatternKind::Wildcard => {}
        PatternKind::Constructor { constructor } => {
            if !constructor.matches(expected) {
                return false;
            }

            // Splat fields for constructors with arity
            match constructor {
                PatternConstructor::DataConstructor { fields, .. }
                | PatternConstructor::Array { fields } => {
                    specialised.extend_from_slice(fields);
                }
                PatternConstructor::Record { labels, fields } => {
                    // Aligning record fields may allocate wildcard patterns,
                    // so only records release the borrow on state.patterns.
                    let (labels, fields) = (labels.clone(), fields.clone());
                    specialise_record_fields_into(state, expected, &labels, &fields, specialised);
                }
                _ => {}
            }
        }
    }

    normalise_specialised_fields(state, expected, initial_length, specialised);
    specialised.extend_from_slice(tail_columns);
    true
}

fn normalise_specialised_fields(
    state: &mut CheckState,
    expected: &PatternConstructor,
    initial_length: usize,
    specialised: &mut PatternVector,
) {
    let expected_fields = expected.fields();
    specialised.truncate(initial_length + expected_fields.len());

    let actual_fields = specialised.len() - initial_length;
    for &expected_field in &expected_fields[actual_fields..] {
        let t = state.patterns[expected_field].t;
        specialised.push(state.allocate_wildcard(t));
    }
}

/// Maps the fields of an actual record pattern to the expected (canonical) label set.
///
/// When record patterns in different branches mention different subsets of labels,
/// the actual pattern may have fewer labels than the expected canonical constructor.
/// This function aligns the actual fields to the expected label positions, inserting
/// wildcard patterns for any labels present in the expected set but absent from the
/// actual pattern.
fn specialise_record_fields_into(
    state: &mut CheckState,
    expected: &PatternConstructor,
    actual_labels: &[SmolStr],
    actual_fields: &[PatternId],
    specialised: &mut PatternVector,
) {
    let PatternConstructor::Record { labels: expected_labels, fields: expected_fields } = expected
    else {
        specialised.extend_from_slice(actual_fields);
        return;
    };

    // Fast path: labels match exactly.
    if actual_labels == expected_labels.as_slice() {
        specialised.extend_from_slice(actual_fields);
        return;
    }

    for (expected_label, &expected_field) in expected_labels.iter().zip(expected_fields.iter()) {
        let actual_field = actual_labels
            .iter()
            .position(|label| label == expected_label)
            .and_then(|position| actual_fields.get(position));
        if let Some(&actual_field) = actual_field {
            specialised.push(actual_field);
        } else {
            let t = state.patterns[expected_field].t;
            specialised.push(state.allocate_wildcard(t));
        }
    }
}

fn default_matrix(state: &CheckState, matrix: &PatternMatrix) -> PatternMatrix {
    let columns = matrix.columns - 1;
    let mut default = if columns == 0 {
        PatternMatrix::new(0)
    } else {
        let default_rows = matrix
            .iter()
            .filter(|row| matches!(state.patterns[row[0]].kind, PatternKind::Wildcard))
            .count();
        PatternMatrix::with_capacity(columns, default_rows)
    };
    for row in matrix {
        let [first_column, ref default_columns @ ..] = row[..] else {
            unreachable!("invariant violated: default_matrix processed empty row");
        };
        if let PatternKind::Wildcard = state.patterns[first_column].kind {
            default.push(default_columns);
        }
    }
    default
}

/// Key for identifying a unique constructor.
#[derive(Clone, PartialEq, Eq, Hash)]
enum ConstructorKey {
    Data(FileId, TermItemId),
    Record,
    Array(usize),
    Boolean(bool),
    Integer(i32),
    Number(bool, SmolStr),
    String(lowering::StringLiteral),
    Char(char),
}

impl ConstructorKey {
    fn from_pattern_constructor(pc: &PatternConstructor) -> Self {
        match pc {
            PatternConstructor::DataConstructor { file_id, item_id, .. } => {
                ConstructorKey::Data(*file_id, *item_id)
            }
            // All record constructors share the same key (single constructor semantics)
            PatternConstructor::Record { .. } => ConstructorKey::Record,
            // Array constructors are keyed by their length
            PatternConstructor::Array { fields } => ConstructorKey::Array(fields.len()),
            PatternConstructor::Boolean(b) => ConstructorKey::Boolean(*b),
            PatternConstructor::Integer(i) => ConstructorKey::Integer(*i),
            PatternConstructor::Number(negative, n) => {
                let n = SmolStr::clone(n);
                ConstructorKey::Number(*negative, n)
            }
            PatternConstructor::String(s) => {
                let s = s.clone();
                ConstructorKey::String(s)
            }
            PatternConstructor::Char(c) => ConstructorKey::Char(*c),
        }
    }
}

#[derive(Clone, Debug)]
struct Sigma {
    constructors: Vec<PatternConstructor>,
}

#[derive(Clone, Debug)]
enum MissingConstructor {
    DataConstructor { file_id: FileId, item_id: TermItemId, fields: Vec<TypeId> },
    Boolean(bool),
}

/// Extracts the sigma, a set of constructors from the first column of the matrix.
///
/// Returns a list of unique constructors seen in the first column, keeping one
/// representative [`PatternConstructor`] per distinct constructor. Other patterns
/// like wildcards, records, and arrays are ignored for now.
fn collect_sigma(state: &CheckState, matrix: &PatternMatrix) -> Sigma {
    let mut seen = FxHashSet::default();
    let mut constructors = vec![];

    for row in matrix {
        let [first_column, ..] = row[..] else {
            continue;
        };
        if let PatternKind::Constructor { constructor } = &state.patterns[first_column].kind {
            let key = ConstructorKey::from_pattern_constructor(constructor);
            if seen.insert(key) {
                constructors.push(constructor.clone());
            }
        }
    }

    // Canonicalise record constructors to include all labels from the matrix.
    // Different record patterns may mention different subsets of the row type,
    // and the specialisation algorithm requires a consistent arity.
    if let Some(index) =
        constructors.iter().position(|c| matches!(c, PatternConstructor::Record { .. }))
    {
        let record = constructors.remove(index);
        let canonical = canonicalise_record_constructor(state, record, matrix);
        constructors.insert(index, canonical);
    }

    Sigma { constructors }
}

/// Checks whether the set of constructors (sigma) is complete for the scrutinee type.
///
/// A sigma is complete if it contains all constructors of the data type.
/// For Boolean, both true and false must be present.
/// For records, there is exactly one constructor, so any record pattern makes sigma complete.
/// For other literal constructors (Integer, Number, String, Char), sigma is never complete
/// (infinite domains).
/// If we can't determine the type or its constructors, we conservatively return false.
fn sigma_is_complete<Q>(context: &CheckContext<Q>, sigma: &Sigma) -> QueryResult<bool>
where
    Q: ExternalQueries,
{
    // Empty sigma is never complete
    let Some(first) = sigma.constructors.first() else {
        return Ok(false);
    };

    match first {
        PatternConstructor::DataConstructor { file_id, item_id, .. } => {
            // Get the indexed module for the constructor's file
            let indexed = context.queries.indexed(*file_id)?;

            // Find the type this constructor belongs to
            let Some(type_item_id) = indexed.constructor_type(*item_id) else {
                return Ok(false);
            };

            // Get all constructors for this type
            let all_constructors: FxHashSet<TermItemId> =
                indexed.data_constructors(type_item_id).collect();

            // Check if sigma covers all constructors
            let sigma_terms: FxHashSet<TermItemId> = sigma
                .constructors
                .iter()
                .filter_map(|c| match c {
                    PatternConstructor::DataConstructor { item_id, .. } => Some(*item_id),
                    _ => None,
                })
                .collect();

            Ok(all_constructors.iter().all(|term_id| sigma_terms.contains(term_id)))
        }
        // Records have exactly one constructor, so sigma is always complete for records
        PatternConstructor::Record { .. } => Ok(true),
        // Arrays have infinite possible lengths, so sigma is never complete
        PatternConstructor::Array { .. } => Ok(false),
        PatternConstructor::Boolean(_) => {
            // Boolean is complete when both true and false are present
            let has_true =
                sigma.constructors.iter().any(|c| matches!(c, PatternConstructor::Boolean(true)));
            let has_false =
                sigma.constructors.iter().any(|c| matches!(c, PatternConstructor::Boolean(false)));
            Ok(has_true && has_false)
        }
        // Other literal constructors have infinite domains, so they're never complete
        PatternConstructor::Integer(_)
        | PatternConstructor::Number(_, _)
        | PatternConstructor::String(_)
        | PatternConstructor::Char(_) => Ok(false),
    }
}

/// Finds the first constructor of the scrutinee type that is not in the sigma.
fn first_missing_constructor<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    scrutinee_type: TypeId,
    constructors: &[PatternConstructor],
) -> QueryResult<Option<MissingConstructor>>
where
    Q: ExternalQueries,
{
    let Some(first_constructor) = constructors.first() else {
        return Ok(None);
    };

    match first_constructor {
        PatternConstructor::DataConstructor { file_id, item_id, .. } => {
            let indexed = context.queries.indexed(*file_id)?;

            let Some(type_item_id) = indexed.constructor_type(*item_id) else {
                return Ok(None);
            };

            let sigma: FxHashSet<TermItemId> = constructors
                .iter()
                .filter_map(|c| match c {
                    PatternConstructor::DataConstructor { item_id, .. } => Some(*item_id),
                    _ => None,
                })
                .collect();

            let mut data_constructors = indexed.data_constructors(type_item_id);
            let Some(missing_item_id) = data_constructors.find(|item_id| !sigma.contains(item_id))
            else {
                return Ok(None);
            };

            let arguments = extract_all_applications(state, context, scrutinee_type)?;
            let fields =
                constructor_field_types(state, context, *file_id, missing_item_id, &arguments)?;

            Ok(Some(MissingConstructor::DataConstructor {
                file_id: *file_id,
                item_id: missing_item_id,
                fields,
            }))
        }
        // Arrays have infinite possible lengths, so we don't report specific missing values.
        // The algorithm will fall back to wildcard suggestion.
        PatternConstructor::Array { .. } => Ok(None),
        PatternConstructor::Boolean(_) => {
            // Check which boolean values are missing
            let has_true =
                constructors.iter().any(|c| matches!(c, PatternConstructor::Boolean(true)));
            let has_false =
                constructors.iter().any(|c| matches!(c, PatternConstructor::Boolean(false)));
            if !has_true {
                Ok(Some(MissingConstructor::Boolean(true)))
            } else if !has_false {
                Ok(Some(MissingConstructor::Boolean(false)))
            } else {
                Ok(None)
            }
        }
        // Other literal constructors have infinite domains, so we don't report specific missing values
        _ => Ok(None),
    }
}

fn constructor_field_types<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    file_id: FileId,
    term_id: TermItemId,
    arguments: &[TypeId],
) -> QueryResult<Vec<TypeId>>
where
    Q: ExternalQueries,
{
    let constructor_type = if file_id == context.id {
        state.checked.lookup_term_item_type(term_id)
    } else {
        let checked = context.checked_dependency(file_id)?;
        checked.lookup_term_item_type(term_id)
    };

    if let Some(constructor_type) = constructor_type {
        let constructor = instantiate_with_arguments(state, context, constructor_type, arguments)?;
        let toolkit::InspectFunction { arguments: fields, .. } =
            toolkit::inspect_function(state, context, constructor)?;
        Ok(fields)
    } else {
        let arity = get_constructor_arity(context, file_id, term_id)?;
        let unknown = context.unknown("missing constructor field");
        Ok(iter::repeat_n(unknown, arity).collect())
    }
}

/// Extracts type and kind arguments from a type application.
///
/// Peels off [`Type::Application`] and [`Type::KindApplication`] layers,
/// collecting both type and kind application arguments.
fn extract_all_applications<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    applied_type: TypeId,
) -> QueryResult<Vec<TypeId>>
where
    Q: ExternalQueries,
{
    let mut arguments = vec![];
    let mut current_id = applied_type;

    safe_loop! {
        current_id = normalise::expand(state, context, current_id)?;
        match *context.lookup_type(current_id) {
            Type::Application(function, argument) => {
                arguments.push(argument);
                current_id = function;
            }
            Type::KindApplication(function, argument) => {
                arguments.push(argument);
                current_id = function;
            }
            _ => break,
        }
    }

    arguments.reverse();
    Ok(arguments)
}

/// Instantiates [`Type::Forall`] with the provided arguments.
///
/// This function falls back to constructing rigid variables if there's
/// not enough arguments provided.
fn instantiate_with_arguments<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    mut type_id: TypeId,
    arguments: impl AsRef<[TypeId]>,
) -> QueryResult<TypeId>
where
    Q: ExternalQueries,
{
    let mut arguments_iter = arguments.as_ref().iter().copied();

    safe_loop! {
        type_id = normalise::expand(state, context, type_id)?;
        match *context.lookup_type(type_id) {
            Type::Forall(binder_id, inner) => {
                let binder = context.lookup_forall_binder(binder_id);
                let argument_type = if let Some(argument) = arguments_iter.next() {
                    argument
                } else {
                    context.intern_rigid(binder.name, state.depth, binder.kind)
                };
                type_id = SubstituteName::one(state, context, binder.name, argument_type, inner)?;
            }
            _ => break,
        }
    }

    Ok(type_id)
}

/// Gets the arity (number of fields) of a constructor.
fn get_constructor_arity<Q>(
    context: &CheckContext<Q>,
    file_id: FileId,
    term_id: TermItemId,
) -> QueryResult<usize>
where
    Q: ExternalQueries,
{
    let on_lowered = |lowered: &lowering::LoweredModule| {
        if let Some(lowering::TermItemKind::Constructor { arguments }) =
            lowered.tree.get_term_item_kind(term_id)
        {
            arguments.len()
        } else {
            0
        }
    };
    if file_id == context.id {
        let lowered = &context.lowered;
        Ok(on_lowered(lowered))
    } else {
        let lowered = context.queries.lowered(file_id)?;
        Ok(on_lowered(&lowered))
    }
}

pub struct ExhaustivenessReport {
    pub missing: Option<Vec<SmolStr>>,
    pub redundant: Vec<SmolStr>,
}

pub fn check_lambda_patterns<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    pattern_types: &[TypeId],
    binders: &[lowering::BinderId],
) -> QueryResult<ExhaustivenessReport>
where
    Q: ExternalQueries,
{
    if pattern_types.is_empty() {
        return Ok(ExhaustivenessReport { missing: None, redundant: vec![] });
    }

    let unconditional =
        collect_unconditional_rows(state, context, &[binders], pattern_types, |binders| {
            (binders, &None)
        })?;

    check_exhaustiveness_core(state, context, pattern_types, unconditional)
}

pub fn check_case_patterns<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    pattern_types: &[TypeId],
    branches: &[lowering::CaseBranch],
) -> QueryResult<ExhaustivenessReport>
where
    Q: ExternalQueries,
{
    if pattern_types.is_empty() {
        return Ok(ExhaustivenessReport { missing: None, redundant: vec![] });
    }

    let unconditional = collect_unconditional_rows(
        state,
        context,
        branches,
        pattern_types,
        |branch: &lowering::CaseBranch| (&branch.binders, &branch.guarded_expression),
    )?;

    check_exhaustiveness_core(state, context, pattern_types, unconditional)
}

pub fn check_equation_patterns<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    pattern_types: &[TypeId],
    equations: &[lowering::Equation],
) -> QueryResult<ExhaustivenessReport>
where
    Q: ExternalQueries,
{
    if pattern_types.is_empty() {
        return Ok(ExhaustivenessReport { missing: None, redundant: vec![] });
    }

    let unconditional = collect_unconditional_rows(
        state,
        context,
        equations,
        pattern_types,
        |equation: &lowering::Equation| (&equation.binders, &equation.guarded),
    )?;

    check_exhaustiveness_core(state, context, pattern_types, unconditional)
}

/// Returns `true` if any alternative in a conditional guard set is trivially true.
fn has_trivially_true_alternative<Q>(
    context: &CheckContext<Q>,
    pattern_guarded: &[lowering::PatternGuarded],
) -> bool
where
    Q: ExternalQueries,
{
    pattern_guarded.iter().any(|pg| {
        !pg.pattern_guards.is_empty()
            && pg.pattern_guards.iter().all(|g| is_trivially_true_guard(context, g))
    })
}

/// Returns `true` if the guard is `true` or `otherwise` from `Data.Boolean`.
fn is_trivially_true_guard<Q>(context: &CheckContext<Q>, guard: &lowering::PatternGuard) -> bool
where
    Q: ExternalQueries,
{
    if let Some(binder_id) = guard.binder {
        return is_irrefutable_binder(context, binder_id);
    }
    let Some(expression_id) = guard.expression else {
        return false;
    };
    is_trivially_true_expression(context, expression_id)
}

fn is_trivially_true_expression<Q>(
    context: &CheckContext<Q>,
    expression_id: lowering::ExpressionId,
) -> bool
where
    Q: ExternalQueries,
{
    let Some(kind) = context.lowered.tree.get_expression_kind(expression_id) else {
        return false;
    };
    match kind {
        lowering::ExpressionKind::Boolean { boolean: true } => true,
        lowering::ExpressionKind::Variable {
            resolution: Some(lowering::TermVariableResolution::Reference(file_id, term_id)),
        } => context.known_terms.otherwise == Some((*file_id, *term_id)),
        lowering::ExpressionKind::Parenthesized { parenthesized: Some(expression_id) }
        | lowering::ExpressionKind::Typed { expression: Some(expression_id), .. } => {
            is_trivially_true_expression(context, *expression_id)
        }
        _ => false,
    }
}

fn is_irrefutable_binder<Q>(context: &CheckContext<Q>, binder_id: lowering::BinderId) -> bool
where
    Q: ExternalQueries,
{
    let Some(kind) = context.lowered.tree.get_binder_kind(binder_id) else {
        return false;
    };
    match kind {
        lowering::BinderKind::Variable { .. } | lowering::BinderKind::Wildcard => true,
        lowering::BinderKind::Named { binder, .. }
        | lowering::BinderKind::Parenthesized { parenthesized: binder }
        | lowering::BinderKind::Typed { binder, .. } => {
            binder.is_some_and(|binder| is_irrefutable_binder(context, binder))
        }
        _ => false,
    }
}

fn collect_unconditional_rows<Q, T, F>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    items: &[T],
    pattern_types: &[TypeId],
    to_binders: F,
) -> QueryResult<PatternMatrix>
where
    Q: ExternalQueries,
    F: Fn(&T) -> (&[lowering::BinderId], &Option<lowering::GuardedExpression>),
{
    let mut pattern_rows = PatternMatrix::new(pattern_types.len());
    for item in items {
        let (binders, guarded) = to_binders(item);

        match guarded {
            Some(lowering::GuardedExpression::Unconditional { .. }) | None => {}
            Some(lowering::GuardedExpression::Conditionals { pattern_guarded }) => {
                if !has_trivially_true_alternative(context, pattern_guarded) {
                    continue;
                }
            }
        }

        let mut pattern_row = vec![];
        for &binder_id in binders {
            pattern_row.push(convert::convert_binder(state, context, binder_id)?);
        }

        pattern_rows.normalise_recovery_row(&mut pattern_row, |column| {
            state.allocate_wildcard(pattern_types[column])
        });

        if !pattern_row.is_empty() {
            pattern_rows.push(&pattern_row);
        }
    }
    Ok(pattern_rows)
}

fn check_exhaustiveness_core<Q>(
    state: &mut CheckState,
    context: &CheckContext<Q>,
    pattern_types: &[TypeId],
    unconditional: PatternMatrix,
) -> QueryResult<ExhaustivenessReport>
where
    Q: ExternalQueries,
{
    let mut redundant = vec![];
    let mut matrix = PatternMatrix::new(unconditional.columns);
    for vector in &unconditional {
        let useful = algorithm_u(state, context, &matrix, vector)?;
        if useful {
            matrix.push(vector);
        } else {
            redundant.push(pretty::pretty_witness(context, state, vector));
        }
    }

    let query: PatternVector = pattern_types.iter().map(|&t| state.allocate_wildcard(t)).collect();
    let witnesses = algorithm_m(state, context, &unconditional, &query)?;
    let missing = witnesses.map(|witnesses| {
        witnesses
            .iter()
            .take(5)
            .map(|witness| pretty::pretty_witness(context, state, witness))
            .collect()
    });

    Ok(ExhaustivenessReport { missing, redundant })
}

#[cfg(test)]
mod tests {
    use std::num::NonZeroU32;

    use super::{PatternId, PatternMatrix};

    fn pattern_id(value: u32) -> PatternId {
        PatternId::new(NonZeroU32::new(value).unwrap())
    }

    #[test]
    fn nonempty_zero_column_matrix_preserves_its_row() {
        let mut matrix = PatternMatrix::new(0);
        matrix.push(&[]);
        matrix.push(&[]);

        assert!(!matrix.is_empty());
        assert_eq!(matrix.rows, 2);
        assert_eq!(matrix.iter().collect::<Vec<_>>(), vec![&[][..], &[][..]]);
    }

    #[test]
    fn ragged_recovery_row_preserves_the_declared_width() {
        let mut matrix = PatternMatrix::new(2);
        let mut short_row = vec![pattern_id(1)];
        let mut long_row = vec![pattern_id(2), pattern_id(3), pattern_id(4)];

        matrix.normalise_recovery_row(&mut short_row, |column| pattern_id(column as u32 + 4));
        matrix.normalise_recovery_row(&mut long_row, |_| unreachable!());
        matrix.push(&short_row);
        matrix.push(&long_row);

        assert_eq!(short_row, vec![pattern_id(1), pattern_id(5)]);
        assert_eq!(long_row, vec![pattern_id(2), pattern_id(3)]);
        assert_eq!(matrix.iter().collect::<Vec<_>>(), vec![short_row, long_row]);
    }

    #[test]
    #[should_panic(expected = "assertion `left == right` failed")]
    fn matrix_rejects_nonrectangular_rows() {
        let mut matrix = PatternMatrix::new(2);
        matrix.push(&[pattern_id(1)]);
    }

    #[test]
    fn row_iterator_reports_its_remaining_length() {
        let mut matrix = PatternMatrix::new(1);
        matrix.push(&[pattern_id(1)]);
        matrix.push(&[pattern_id(2)]);

        let mut rows = matrix.iter();
        assert_eq!(rows.len(), 2);
        assert_eq!(rows.next(), Some(&[pattern_id(1)][..]));
        assert_eq!(rows.len(), 1);
        assert_eq!(rows.next(), Some(&[pattern_id(2)][..]));
        assert_eq!(rows.len(), 0);
        assert_eq!(rows.next(), None);
    }
}
