[package]
name = "iris-progress"
version = "0.1.0"
edition = "2024"
authors = ["Justin Garcia <git@purefunctor.me>"]
license = "BSD-3-Clause"
description = "Terminal package progress reporting for Iris."
repository = "https://github.com/purefunctor/purescript-iris"

[dependencies]
console = "0.16.4"
itertools = "0.15.0"
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm"] }
terminal-colorsaurus = "1.0.3"
