[package]
name = "iris-lsp"
version = "0.1.0"
edition = "2024"
authors = ["Justin Garcia <git@purefunctor.me>"]
license.workspace = true
description = "PureScript language server implementation for Iris."
repository = "https://github.com/purefunctor/purescript-iris"

[dependencies]
iris-lsp-server = { version = "0.1.0", path = "../iris-lsp-server" }
iris-lsp-workspace = { version = "0.1.0", path = "../iris-lsp-workspace" }
tokio = { version = "1.53.1", features = ["rt"] }

[dev-dependencies]
iris-lsp-workspace = { version = "0.1.0", path = "../iris-lsp-workspace", features = ["test-support"] }
lsp-server = "0.10.0"
serde_json = "1.0.151"
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["macros", "rt", "time"] }
url = "2.5.8"
