[package]
name = "building"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
building-types = { version = "0.1.0", path = "../building-types" }
checking = { version = "0.1.0", path = "../../compiler-frontend/checking" }
documenting = { version = "0.1.0", path = "../../compiler-frontend/documenting" }
files = { version = "0.1.0", path = "../files" }
foreign-javascript = { version = "0.1.0", path = "../../compiler-backend/foreign-javascript" }
functional = { version = "0.1.0", path = "../../compiler-backend/functional" }
indexing = { version = "0.1.0", path = "../../compiler-frontend/indexing" }
interner = { version = "0.1.0", path = "../interner" }
javascript = { version = "0.1.0", path = "../../compiler-backend/javascript" }
lexing = { version = "0.1.0", path = "../../compiler-frontend/lexing" }
lock_api = "0.4.14"
lowering = { version = "0.1.0", path = "../../compiler-frontend/lowering" }
parking_lot = "0.12.5"
parsing = { version = "0.1.0", path = "../../compiler-frontend/parsing" }
prim-constants = { version = "0.1.0", path = "../prim-constants" }
rayon = "1.12.0"
resolving = { version = "0.1.0", path = "../../compiler-frontend/resolving" }
rustc-hash = "2.1.3"
stabilizing = { version = "0.1.0", path = "../../compiler-frontend/stabilizing" }
sugar = { version = "0.1.0", path = "../../compiler-frontend/sugar" }
smol_str = "0.3.6"
thread_local = "1.1.10"

[dev-dependencies]
la-arena = "0.3.1"
