[package]
name = "parsing"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
drop_bomb = "0.1.5"
lexing = { version = "0.1.0", path = "../lexing" }
smol_str = "0.3.6"
syntree = "0.18.0"
syntax = { version = "0.1.0", path = "../syntax" }

[dev-dependencies]
insta = "1.48.0"
test_each_file = "0.3.7"
