[package]
name = "resolving"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
building-types = { version = "0.1.0", path = "../../compiler-core/building-types" }
files = { version = "0.1.0", path = "../../compiler-core/files" }
indexing = { version = "0.1.0", path = "../indexing" }
rustc-hash = "2.1.3"
smol_str = "0.3.6"

[dev-dependencies]
itertools = "0.15.0"
lexing = { path = "../lexing" }
lowering = { path = "../lowering" }
parsing = { path = "../parsing" }
paste = "1.0.15"
