[package]
name = "purescript-iris-v2"
version = "0.1.0"
edition = "2024"
authors = ["Justin Garcia <git@purefunctor.me>"]
license = "BSD-3-Clause"
description = "Experimental PureScript compiler command-line interface."
readme = "../../README.md"
homepage = "https://github.com/purefunctor/purescript-iris"
repository = "https://github.com/purefunctor/purescript-iris"
keywords = ["purescript", "compiler"]
categories = ["compilers"]

[[bin]]
name = "iris-v2"
path = "src/bin/iris.rs"

[dependencies]
iris-build = { version = "0.1.0", path = "../build" }
itertools = "0.15.0"
usage = { package = "usage-rs", version = "6.8.0" }
