[package]
name = "iris-documentation"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
building = { version = "0.1.0", path = "../../compiler-core/building" }
checking = { version = "0.1.0", path = "../../compiler-frontend/checking" }
documenting = { version = "0.1.0", path = "../../compiler-frontend/documenting" }
files = { version = "0.1.0", path = "../../compiler-core/files" }
indexing = { version = "0.1.0", path = "../../compiler-frontend/indexing" }
lowering = { version = "0.1.0", path = "../../compiler-frontend/lowering" }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
ts-rs = { version = "12.0.1", default-features = false, features = ["serde-compat"] }
