[package]
name = "iris-cli"
version = "0.1.1"
edition = "2024"
authors = ["Justin Garcia <git@purefunctor.me>"]
license.workspace = true
description = "PureScript compiler command-line interface."
readme = "../../README.md"
homepage = "https://github.com/purefunctor/purescript-iris"
repository = "https://github.com/purefunctor/purescript-iris"
keywords = ["purescript", "compiler"]
categories = ["compilers"]

[[bin]]
name = "iris"
path = "src/bin/iris.rs"

[dependencies]
directories = "6.0.0"
iris-build = { version = "0.1.0", path = "../iris-build" }
iris-lsp = { version = "0.1.0", path = "../iris-lsp" }
iris-package = { version = "0.1.0", path = "../iris-package" }
iris-watch = { version = "0.1.0", path = "../iris-watch" }
iris-watch-server = { version = "0.1.0", path = "../iris-watch-server" }
itertools = "0.15.0"
mimalloc = "0.1.52"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
usage = { package = "usage-rs", version = "6.11.0" }
