[package]
name = "iris-cli"
version = "0.1.0"
edition = "2024"
authors = ["Justin Garcia <git@purefunctor.me>"]
license = "BSD-3-Clause"
description = "PureScript compiler command-line interface."
readme = "../../README.md"
homepage = "https://github.com/purefunctor/purescript-iris"
repository = "https://github.com/purefunctor/purescript-iris"
keywords = ["purescript", "compiler"]
categories = ["compilers"]

[[bin]]
name = "iris"
path = "src/bin/iris.rs"

[dependencies]
configuration = { version = "0.1.0", path = "../../compiler-lsp/configuration" }
iris-build = { version = "0.1.0", path = "../iris-build" }
iris-lsp = { version = "0.1.0", path = "../iris-lsp" }
iris-package = { version = "0.1.0", path = "../iris-package" }
iris-watch = { version = "0.1.0", path = "../iris-watch" }
itertools = "0.15.0"
serde_json = "1.0.151"
thiserror = "2.0.20"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
usage = { package = "usage-rs", version = "6.8.0" }
