[package]
name = "tests-integration"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
analyzer = { version = "0.1.0", path = "../compiler-lsp/analyzer" }
async-lsp = "0.2.4"
building = { version = "0.1.0", path = "../compiler-core/building" }
checking = { version = "0.1.0", path = "../compiler-frontend/checking" }
diagnostics = { version = "0.1.0", path = "../compiler-frontend/diagnostics" }
documentation = { version = "0.1.0", path = "../compiler-lsp/documentation" }
files = { version = "0.1.0", path = "../compiler-core/files" }
functional = { version = "0.1.0", path = "../compiler-backend/functional" }
glob = "0.3.4"
indexing = { version = "0.1.0", path = "../compiler-frontend/indexing" }
interner = { version = "0.1.0", path = "../compiler-core/interner" }
iris-build = { version = "0.1.0", path = "../compiler-bin/iris-build" }
itertools = "0.15.0"
insta = "1.48.0"
javascript = { version = "0.1.0", path = "../compiler-backend/javascript" }
line-index = "0.1.2"
lowering = { version = "0.1.0", path = "../compiler-frontend/lowering" }
lsp-types.workspace = true
prim-constants = { version = "0.1.0", path = "../compiler-core/prim-constants" }
process_control = "5.2"
serde_json = "1.0"
similar = "3"
stabilizing = { version = "0.1.0", path = "../compiler-frontend/stabilizing" }
sugar = { version = "0.1.0", path = "../compiler-frontend/sugar" }
syntax = { version = "0.1.0", path = "../compiler-frontend/syntax" }
tabled = "0.22.0"
tempfile = "3.27.0"
tests-support = { path = "../tests-support" }
url = "2.5.8"

[dev-dependencies]
datatest-stable = "0.3"

[[test]]
name = "compiler"
harness = false

[[test]]
name = "lowering"
harness = false

[[test]]
name = "resolving"
harness = false

[[test]]
name = "lsp"
harness = false

[[test]]
name = "lifecycle"
harness = false

[[test]]
name = "docs"
harness = false
